version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bde_database
    ports:
      - "5000:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      # - ./insert-data.sql:/docker-entrypoint-initdb.d/insert-data.sql
volumes:
  mysql_data: